Resources:
  HellolambdaHandlerServiceRole0FDFAB5F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: AwsLambda1Stack/HellolambdaHandler/ServiceRole/Resource
  HellolambdaHandler0C0D53EB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adS3BucketBEB953F3
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adS3VersionKeyC0C08E97
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adS3VersionKeyC0C08E97
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - HellolambdaHandlerServiceRole0FDFAB5F
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - HellolambdaHandlerServiceRole0FDFAB5F
    Metadata:
      aws:cdk:path: AwsLambda1Stack/HellolambdaHandler/Resource
      aws:asset:path: /home/ai-cnc-bc/Desktop/AWS-Server/aws-lambda1/lambda
      aws:asset:property: Code
  MylambdaAPICAC745C0:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MylambdaAPI
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Resource
  MylambdaAPICloudWatchRole9E373ACA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/CloudWatchRole/Resource
  MylambdaAPIAccountAF01B5C5:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - MylambdaAPICloudWatchRole9E373ACA
          - Arn
    DependsOn:
      - MylambdaAPICAC745C0
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Account
  MylambdaAPIDeployment3B085A084a809b90e91f789745a422cfcecc5b88:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: MylambdaAPICAC745C0
      Description: Automatically created by the RestApi construct
    DependsOn:
      - MylambdaAPIcarsGet3E4B1264
      - MylambdaAPIcarsC5EBAF42
      - MylambdaAPIcollectAPIGET00271E22
      - MylambdaAPIcollectAPI52817B26
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Deployment/Resource
  MylambdaAPIDeploymentStageprod710BB000:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: MylambdaAPICAC745C0
      DeploymentId:
        Ref: MylambdaAPIDeployment3B085A084a809b90e91f789745a422cfcecc5b88
      StageName: prod
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/DeploymentStage.prod/Resource
  MylambdaAPIcarsC5EBAF42:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - MylambdaAPICAC745C0
          - RootResourceId
      PathPart: cars
      RestApiId:
        Ref: MylambdaAPICAC745C0
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/cars/Resource
  MylambdaAPIcarsGetApiPermissionAwsLambda1StackMylambdaAPI67A0691CGETcars72379EB4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPICAC745C0
            - /
            - Ref: MylambdaAPIDeploymentStageprod710BB000
            - /GET/cars
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/cars/Get/ApiPermission.AwsLambda1StackMylambdaAPI67A0691C.GET..cars
  MylambdaAPIcarsGetApiPermissionTestAwsLambda1StackMylambdaAPI67A0691CGETcarsF034184E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPICAC745C0
            - /test-invoke-stage/GET/cars
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/cars/Get/ApiPermission.Test.AwsLambda1StackMylambdaAPI67A0691C.GET..cars
  MylambdaAPIcarsGet3E4B1264:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: MylambdaAPIcarsC5EBAF42
      RestApiId:
        Ref: MylambdaAPICAC745C0
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HellolambdaHandler0C0D53EB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/cars/Get/Resource
  MylambdaAPIcollectAPI52817B26:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - MylambdaAPICAC745C0
          - RootResourceId
      PathPart: collectAPI
      RestApiId:
        Ref: MylambdaAPICAC745C0
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/collectAPI/Resource
  MylambdaAPIcollectAPIGETApiPermissionAwsLambda1StackMylambdaAPI67A0691CGETcollectAPIA5E54D61:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPICAC745C0
            - /
            - Ref: MylambdaAPIDeploymentStageprod710BB000
            - /GET/collectAPI
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/collectAPI/GET/ApiPermission.AwsLambda1StackMylambdaAPI67A0691C.GET..collectAPI
  MylambdaAPIcollectAPIGETApiPermissionTestAwsLambda1StackMylambdaAPI67A0691CGETcollectAPIFBE535EB:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPICAC745C0
            - /test-invoke-stage/GET/collectAPI
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/collectAPI/GET/ApiPermission.Test.AwsLambda1StackMylambdaAPI67A0691C.GET..collectAPI
  MylambdaAPIcollectAPIGET00271E22:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: MylambdaAPIcollectAPI52817B26
      RestApiId:
        Ref: MylambdaAPICAC745C0
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HellolambdaHandler0C0D53EB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI/Default/collectAPI/GET/Resource
  MylambdaAPI1231D6ABB:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MylambdaAPI1
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Resource
  MylambdaAPI1CloudWatchRoleBDD30EF0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/CloudWatchRole/Resource
  MylambdaAPI1AccountF505D819:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - MylambdaAPI1CloudWatchRoleBDD30EF0
          - Arn
    DependsOn:
      - MylambdaAPI1231D6ABB
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Account
  MylambdaAPI1DeploymentEC003B69daa9469b44674f2d2abfacd089a19293:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: MylambdaAPI1231D6ABB
      Description: Automatically created by the RestApi construct
    DependsOn:
      - MylambdaAPI1testcar1Get6C361991
      - MylambdaAPI1testcar164C0F538
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Deployment/Resource
  MylambdaAPI1DeploymentStageprodF15ED75A:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: MylambdaAPI1231D6ABB
      DeploymentId:
        Ref: MylambdaAPI1DeploymentEC003B69daa9469b44674f2d2abfacd089a19293
      StageName: prod
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/DeploymentStage.prod/Resource
  MylambdaAPI1testcar164C0F538:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - MylambdaAPI1231D6ABB
          - RootResourceId
      PathPart: testcar1
      RestApiId:
        Ref: MylambdaAPI1231D6ABB
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Default/testcar1/Resource
  MylambdaAPI1testcar1GetApiPermissionAwsLambda1StackMylambdaAPI1142A9EBCGETtestcar131499AAA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPI1231D6ABB
            - /
            - Ref: MylambdaAPI1DeploymentStageprodF15ED75A
            - /GET/testcar1
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Default/testcar1/Get/ApiPermission.AwsLambda1StackMylambdaAPI1142A9EBC.GET..testcar1
  MylambdaAPI1testcar1GetApiPermissionTestAwsLambda1StackMylambdaAPI1142A9EBCGETtestcar1A318F68D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HellolambdaHandler0C0D53EB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: MylambdaAPI1231D6ABB
            - /test-invoke-stage/GET/testcar1
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Default/testcar1/Get/ApiPermission.Test.AwsLambda1StackMylambdaAPI1142A9EBC.GET..testcar1
  MylambdaAPI1testcar1Get6C361991:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: MylambdaAPI1testcar164C0F538
      RestApiId:
        Ref: MylambdaAPI1231D6ABB
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HellolambdaHandler0C0D53EB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: AwsLambda1Stack/MylambdaAPI1/Default/testcar1/Get/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.77.0,@aws-cdk/assets=1.78.0,@aws-cdk/aws-apigateway=1.78.0,@aws-cdk/aws-applicationautoscaling=1.78.0,@aws-cdk/aws-autoscaling-common=1.78.0,@aws-cdk/aws-cloudwatch=1.78.0,@aws-cdk/aws-codeguruprofiler=1.78.0,@aws-cdk/aws-ec2=1.78.0,@aws-cdk/aws-ecr=1.78.0,@aws-cdk/aws-ecr-assets=1.78.0,@aws-cdk/aws-events=1.78.0,@aws-cdk/aws-iam=1.78.0,@aws-cdk/aws-kms=1.78.0,@aws-cdk/aws-lambda=1.78.0,@aws-cdk/aws-logs=1.78.0,@aws-cdk/aws-s3=1.78.0,@aws-cdk/aws-s3-assets=1.78.0,@aws-cdk/aws-sqs=1.78.0,@aws-cdk/aws-ssm=1.78.0,@aws-cdk/cloud-assembly-schema=1.78.0,@aws-cdk/core=1.78.0,@aws-cdk/cx-api=1.78.0,@aws-cdk/region-info=1.78.0,jsii-runtime=node.js/v12.19.1
    Metadata:
      aws:cdk:path: AwsLambda1Stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adS3BucketBEB953F3:
    Type: String
    Description: S3 bucket for asset "7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04ad"
  AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adS3VersionKeyC0C08E97:
    Type: String
    Description: S3 key for asset version "7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04ad"
  AssetParameters7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04adArtifactHash1593FF30:
    Type: String
    Description: Artifact hash for asset "7372a3996ab8b6b7670c78e82aeb164d01a2e53c65c93cbbcfd2a595a43f04ad"
Outputs:
  MylambdaAPIEndpoint3973FFE0:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: MylambdaAPICAC745C0
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: MylambdaAPIDeploymentStageprod710BB000
          - /
  MylambdaAPI1EndpointD77DF6AA:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: MylambdaAPI1231D6ABB
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: MylambdaAPI1DeploymentStageprodF15ED75A
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

